inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  SuggestExtensions: false
  Exclude:
    - "/**/bin/*"
    - "/**/config/**/*"
    - "/**/db/**/*"
    - "/**/Rakefile"
    - "/**/config.ru"

Style/MethodCallWithArgsParentheses:
  Exclude:
    - "/**/spec/**/*"
